name: subsonic_api
description: Package that provides a simple API to interact with SubSonic API compatible servers.
version: 0.0.3
repository: https://github.com/f1ammetta/subsonic_api

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.3
  http: ^1.2.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
